/* eslint-disable react/react-in-jsx-scope */
import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import NavHeader from './(components)/NavHeader';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </head>
      <body className={inter.className} >
        <header className="fixed top-0 left-0 right-0 text-center flex justify-between bg-white p-6 shadow-xl z-50">
          <nav className="flex justify-evenly w-1/3">
            <Link href="/" className="text-lg font-sans font-bold whitespace-nowrap">Angora Forms</Link>
            <Link href="/docs" className="text-sm justify-end hover:underline">Docs</Link>
          </nav>
          <nav className="w-1/2 flex justify-evenly">
            <NavHeader />
          </nav>
        </header>
        <div>
          {children}
        </div>
        <footer>
          <h1>hi</h1>
        </footer>
      </body>
    </html>
  );
}

